language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"

env:
  matrix:
    - LARAVEL=5.8.*
    - LARAVEL=^6.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=^6.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit tests
